javascript-typescript:
  - any:
      - '**/*.ts'
      - '**/*.js'

documentation:
  - any:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'
      - 'ROADMAP.md'
      - 'SECURITY.md'

firmware:
  - changed-files:
      - any-glob-to-any-file:
          - firmware/**

software:
  - changed-files:
      - any-glob-to-any-file:
          - software/**

hardware:
  - changed-files:
      - any-glob-to-any-file:
          - hardware/**

website:
  - changed-files:
      - any-glob-to-any-file:
          - website/**

sdk:
  - changed-files:
      - any-glob-to-any-file:
          - sdk/**

cli:
  - changed-files:
      - any-glob-to-any-file:
          - cli/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**

dependencies:
  - any:
      - '**/package.json'
      - '/pnpm-lock.yaml'
      - '/pnpm-workspace.yaml'

config:
  - any:
      - '**/tsconfig.json'
      - '**/jsconfig.json'
      - '**/eslint.config.js'
      - '**/.prettierrc'
      - '**/.stylelintrc'
      - '**/.prettierignore'
      - '**/.gitignore'
      - '**/.npmrc'
      - '**/.commitlintrc.json'
      - '**/.husky/**'
      - '**/.github/**'
      - '**/turbo.json'
      - '**/vite.config.ts'
      - '**/vitest.config.ts'
      - '**/tsconfig.base.json'
      - '**/LICENSE'
      - '**/.gitattributes'
      - '**/.editorconfig'
